In [1]:
# Data Wrangling(Manipulation) with base R and dplyr

# Data wrangling means transforming raw data into a structured and usable format for analysis.

In [2]:
install.packages("dplyr")
library(dplyr)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [80]:

data <- data.frame(
  ID = 1:10,
  Name = c("Shihab", "Kabir","Mahbub", "Pranto", "Nusrat", "Mumu", "Meraj", "Supto", "Mujahid", "Ashik"),
  Age = c(25,30,35,40,28,32,45,29,50,27),
  Salary = c(50000,45000,60000,45000,70000,52000,48000,68000,65000,40000),
  Department = c("HR", "FINANCE", "IT", "HR", "IT", "FINANCE", "IT", "HR", "FINANCE", "IT"),
  Performance_score = c(88,92,85,78,90,94,86,80,89,75)
)

print(data)

   ID    Name Age Salary Department Performance_score
1   1  Shihab  25  50000         HR                88
2   2   Kabir  30  45000    FINANCE                92
3   3  Mahbub  35  60000         IT                85
4   4  Pranto  40  45000         HR                78
5   5  Nusrat  28  70000         IT                90
6   6    Mumu  32  52000    FINANCE                94
7   7   Meraj  45  48000         IT                86
8   8   Supto  29  68000         HR                80
9   9 Mujahid  50  65000    FINANCE                89
10 10   Ashik  27  40000         IT                75

In [11]:
# Filterinng rows

## Base R ##
# Filtering rows where age>30
data[data$Age > 30,]
# If we want to directly access any column without mentionig the name of dataframe(Not a good practice)
attach(data)
data[Age>30,]
detach(data)

# Filtering rows where department is "IT"
data[data$Department == "IT",]

# Filtering rows where Age greater than 30 and Department is Finance
data[data$Age>30 & data$Department == "FINANCE",]

# Filtering rows where department is in a specific set
data[data$Department %in% c("HR","IT"),]

# Exclude rows where department is HR
data[data$Department != "HR",]


## Dplyr ##

# The uniqueness in dplyr is pipe operator(%>%)
# shortcut for pipe operator(%>%): ctrl+shift+M

round(mean(c(44,55,25.45,48.44)),1)
c(44,55,25.4,48.44) %>%
  mean() %>%
  round(2)


# Filtering rows where age>30
filter(data, Age>30)    # without using pipe operator
data %>% filter(Age>30)

# Filtering rows where department is "IT"
data %>% filter(Department == "IT")

# Filtering rows where Age greater than 30 and Department is Finance
data %>% filter(Age >30 & Department == "FINANCE")

# Filtering rows where department is in a specific set
data %>% filter(Department %in% c("HR", "IT"))

# Exclude rows where department is HR
data %>% filter(Department != "HR")

# Selecting/Slicing particular rows
data %>% slice(1:5)
data %>% slice(10)
set.seed(0)
data %>% slice_sample(n = 3)

  ID Name    Age Salary Department Performance_score
3 3  Mahbub  35  60000  IT         85
4 4  Pranto  40  45000  HR         78
6 6  Mumu    32  52000  FINANCE    94
7 7  Meraj   45  48000  IT         86
9 9  Mujahid 50  65000  FINANCE    89

  ID Name    Age Salary Department Performance_score
3 3  Mahbub  35  60000  IT         85
4 4  Pranto  40  45000  HR         78
6 6  Mumu    32  52000  FINANCE    94
7 7  Meraj   45  48000  IT         86
9 9  Mujahid 50  65000  FINANCE    89

   ID Name   Age Salary Department Performance_score
3   3 Mahbub 35  60000  IT         85
5   5 Nusrat 28  70000  IT         90
7   7 Meraj  45  48000  IT         86
10 10 Ashik  27  40000  IT         75

  ID Name    Age Salary Department Performance_score
6 6  Mumu    32  52000  FINANCE    94
9 9  Mujahid 50  65000  FINANCE    89

   ID Name   Age Salary Department Performance_score
1   1 Shihab 25  50000  HR         88
3   3 Mahbub 35  60000  IT         85
4   4 Pranto 40  45000  HR         78
5   5 Nusrat 28  70000  IT         90
7   7 Meraj  45  48000  IT         86
8   8 Supto  29  68000  HR         80
10 10 Ashik  27  40000  IT         75

   ID Name    Age Salary Department Performance_score
2   2 Kabir   30  45000  FINANCE    92
3   3 Mahbub  35  60000  IT         85
5   5 Nusrat  28  70000  IT         90
6   6 Mumu    32  52000  FINANCE    94
7   7 Meraj   45  48000  IT         86
9   9 Mujahid 50  65000  FINANCE    89
10 10 Ashik   27  40000  IT         75

[1] 43.2

[1] 43.21

  ID Name    Age Salary Department Performance_score
1 3  Mahbub  35  60000  IT         85
2 4  Pranto  40  45000  HR         78
3 6  Mumu    32  52000  FINANCE    94
4 7  Meraj   45  48000  IT         86
5 9  Mujahid 50  65000  FINANCE    89

  ID Name    Age Salary Department Performance_score
1 3  Mahbub  35  60000  IT         85
2 4  Pranto  40  45000  HR         78
3 6  Mumu    32  52000  FINANCE    94
4 7  Meraj   45  48000  IT         86
5 9  Mujahid 50  65000  FINANCE    89

  ID Name   Age Salary Department Performance_score
1  3 Mahbub 35  60000  IT         85
2  5 Nusrat 28  70000  IT         90
3  7 Meraj  45  48000  IT         86
4 10 Ashik  27  40000  IT         75

  ID Name    Age Salary Department Performance_score
1 6  Mumu    32  52000  FINANCE    94
2 9  Mujahid 50  65000  FINANCE    89

  ID Name   Age Salary Department Performance_score
1  1 Shihab 25  50000  HR         88
2  3 Mahbub 35  60000  IT         85
3  4 Pranto 40  45000  HR         78
4  5 Nusrat 28  70000  IT         90
5  7 Meraj  45  48000  IT         86
6  8 Supto  29  68000  HR         80
7 10 Ashik  27  40000  IT         75

  ID Name    Age Salary Department Performance_score
1  2 Kabir   30  45000  FINANCE    92
2  3 Mahbub  35  60000  IT         85
3  5 Nusrat  28  70000  IT         90
4  6 Mumu    32  52000  FINANCE    94
5  7 Meraj   45  48000  IT         86
6  9 Mujahid 50  65000  FINANCE    89
7 10 Ashik   27  40000  IT         75

  ID Name   Age Salary Department Performance_score
1 1  Shihab 25  50000  HR         88
2 2  Kabir  30  45000  FINANCE    92
3 3  Mahbub 35  60000  IT         85
4 4  Pranto 40  45000  HR         78
5 5  Nusrat 28  70000  IT         90

  ID Name  Age Salary Department Performance_score
1 10 Ashik 27  40000  IT         75

  ID Name    Age Salary Department Performance_score
1 9  Mujahid 50  65000  FINANCE    89
2 4  Pranto  40  45000  HR         78
3 7  Meraj   45  48000  IT         86

In [8]:
# Selecting columns

## Base R ##
# Select a single columns by name
data[,"Name"]    # Returns a dataframe
data$Name       # Returns a vector

# Select multiple columns by name
data[,c("Name","Age")]

# Select columns by position
data[,c(1,2)]

# Exclude columns by name
data[, !(colnames(data) %in% "Department")]

# Exclude columns by position
data[, -3]


## dplyr ##
# No column selected as vector, all selected as dataframe
# Select a single column by names
data %>% select(Name)

# Select multiple columns by name
data %>% select(ID, Department)

# Select multiple columns by position
data %>% select(1,2,5)

# Exclude columns by names
data %>% select(-Department, -ID)

# Exclude columns by position
data %>% select(-5,-6)

# Select columns based on patterns
data %>% select(starts_with("P"))
data %>% select(contains("age"))

# Select columns based on data type
data %>% select(where(is.numeric))
data %>% select(where(is.character))

 [1] "Shihab"  "Kabir"   "Mahbub"  "Pranto"  "Nusrat"  "Mumu"    "Meraj"
 [8] "Supto"   "Mujahid" "Ashik"

 [1] "Shihab"  "Kabir"   "Mahbub"  "Pranto"  "Nusrat"  "Mumu"    "Meraj"
 [8] "Supto"   "Mujahid" "Ashik"

   Name    Age
1  Shihab  25
2  Kabir   30
3  Mahbub  35
4  Pranto  40
5  Nusrat  28
6  Mumu    32
7  Meraj   45
8  Supto   29
9  Mujahid 50
10 Ashik   27

   ID Name
1   1 Shihab
2   2 Kabir
3   3 Mahbub
4   4 Pranto
5   5 Nusrat
6   6 Mumu
7   7 Meraj
8   8 Supto
9   9 Mujahid
10 10 Ashik

   ID Name    Age Salary Performance_score
1   1 Shihab  25  50000  88
2   2 Kabir   30  45000  92
3   3 Mahbub  35  60000  85
4   4 Pranto  40  45000  78
5   5 Nusrat  28  70000  90
6   6 Mumu    32  52000  94
7   7 Meraj   45  48000  86
8   8 Supto   29  68000  80
9   9 Mujahid 50  65000  89
10 10 Ashik   27  40000  75

   ID Name    Salary Department Performance_score
1   1 Shihab  50000  HR         88
2   2 Kabir   45000  FINANCE    92
3   3 Mahbub  60000  IT         85
4   4 Pranto  45000  HR         78
5   5 Nusrat  70000  IT         90
6   6 Mumu    52000  FINANCE    94
7   7 Meraj   48000  IT         86
8   8 Supto   68000  HR         80
9   9 Mujahid 65000  FINANCE    89
10 10 Ashik   40000  IT         75

   Name
1  Shihab
2  Kabir
3  Mahbub
4  Pranto
5  Nusrat
6  Mumu
7  Meraj
8  Supto
9  Mujahid
10 Ashik

   ID Department
1   1 HR
2   2 FINANCE
3   3 IT
4   4 HR
5   5 IT
6   6 FINANCE
7   7 IT
8   8 HR
9   9 FINANCE
10 10 IT

   ID Name    Department
1   1 Shihab  HR
2   2 Kabir   FINANCE
3   3 Mahbub  IT
4   4 Pranto  HR
5   5 Nusrat  IT
6   6 Mumu    FINANCE
7   7 Meraj   IT
8   8 Supto   HR
9   9 Mujahid FINANCE
10 10 Ashik   IT

   Name    Age Salary Performance_score
1  Shihab  25  50000  88
2  Kabir   30  45000  92
3  Mahbub  35  60000  85
4  Pranto  40  45000  78
5  Nusrat  28  70000  90
6  Mumu    32  52000  94
7  Meraj   45  48000  86
8  Supto   29  68000  80
9  Mujahid 50  65000  89
10 Ashik   27  40000  75

   ID Name    Age Salary
1   1 Shihab  25  50000
2   2 Kabir   30  45000
3   3 Mahbub  35  60000
4   4 Pranto  40  45000
5   5 Nusrat  28  70000
6   6 Mumu    32  52000
7   7 Meraj   45  48000
8   8 Supto   29  68000
9   9 Mujahid 50  65000
10 10 Ashik   27  40000

   Performance_score
1  88
2  92
3  85
4  78
5  90
6  94
7  86
8  80
9  89
10 75

   Age
1  25
2  30
3  35
4  40
5  28
6  32
7  45
8  29
9  50
10 27

   ID Age Salary Performance_score
1   1 25  50000  88
2   2 30  45000  92
3   3 35  60000  85
4   4 40  45000  78
5   5 28  70000  90
6   6 32  52000  94
7   7 45  48000  86
8   8 29  68000  80
9   9 50  65000  89
10 10 27  40000  75

   Name    Department
1  Shihab  HR
2  Kabir   FINANCE
3  Mahbub  IT
4  Pranto  HR
5  Nusrat  IT
6  Mumu    FINANCE
7  Meraj   IT
8  Supto   HR
9  Mujahid FINANCE
10 Ashik   IT

In [14]:
# Creating columns

## Base R ##
# Add a new column with existing value
data$Experience <- c(2,5,10,3,8,4,2,1,1,6)

# Add a constant value
data$Constant_value <- 1

# Add a calculated column
data$Bonus <- data$Salary * data$Performance_score * 0.001

# Add a column using conditional logic
data$High_performer <- ifelse(data$Performance_score >= 85 , TRUE, FALSE)
data$Low_performer <- !data$High_performer
data


## dplyr ##
# Add new columns with computed values
data_01 <- data %>%
  mutate(
  Experience = c(1,2,3,4,5,6,7,8,9,10),
  Constant_value = 1,
  High_performer = Performance_score >= 80,
  Low_performer = !High_performer,
  Bonus = Salary * Performance_score * 0.002
  )

data_01;

   ID Name    Age Salary Department Performance_score Experience Constant_value
1   1 Shihab  25  50000  HR         88                 2         1
2   2 Kabir   30  45000  FINANCE    92                 5         1
3   3 Mahbub  35  60000  IT         85                10         1
4   4 Pranto  40  45000  HR         78                 3         1
5   5 Nusrat  28  70000  IT         90                 8         1
6   6 Mumu    32  52000  FINANCE    94                 4         1
7   7 Meraj   45  48000  IT         86                 2         1
8   8 Supto   29  68000  HR         80                 1         1
9   9 Mujahid 50  65000  FINANCE    89                 1         1
10 10 Ashik   27  40000  IT         75                 6         1
   Bonus High_performer Low_performer
1  4400   TRUE          FALSE
2  4140   TRUE          FALSE
3  5100   TRUE          FALSE
4  3510  FALSE           TRUE
5  6300   TRUE          FALSE
6  4888   TRUE          FALSE
7  4128   TRUE          FALSE
8  5440  FALSE           TRUE
9  5785   TRUE          FALSE
10 3000  FALSE           TRUE

   ID Name    Age Salary Department Performance_score Experience Constant_value
1   1 Shihab  25  50000  HR         88                 1         1
2   2 Kabir   30  45000  FINANCE    92                 2         1
3   3 Mahbub  35  60000  IT         85                 3         1
4   4 Pranto  40  45000  HR         78                 4         1
5   5 Nusrat  28  70000  IT         90                 5         1
6   6 Mumu    32  52000  FINANCE    94                 6         1
7   7 Meraj   45  48000  IT         86                 7         1
8   8 Supto   29  68000  HR         80                 8         1
9   9 Mujahid 50  65000  FINANCE    89                 9         1
10 10 Ashik   27  40000  IT         75                10         1
   Bonus High_performer Low_performer
1   8800  TRUE          FALSE
2   8280  TRUE          FALSE
3  10200  TRUE          FALSE
4   7020 FALSE           TRUE
5  12600  TRUE          FALSE
6   9776  TRUE          FALSE
7   8256  TRUE          FALSE
8  10880  TRUE          FALSE
9  11570  TRUE          FALSE
10  6000 FALSE           TRUE

In [30]:
# Removing columns

## Base R ##
# Remove a column by assigning NULL
data_01$Constant_value <- NULL
data_01

# Removing multiple columns using subset
data_01 <- data_01[,!(colnames(data_01) %in% c("High_performer", "Low_performer"))]
data_01


## dplyr ##
# Removing columns with dplyr
# Removing a single column
data_02 <- data_02 %>% select(-Performance_score)
data_02

# Removing multiple column
data_02 <- data_02 %>% select(-c(High_performer,Low_performer, Constant_value))
data_02

# Remove colums based on condition
data_02 <- data_02 %>% select(-where(is.numeric))
data_02

   ID Name    Age Salary Department Performance_score Experience Bonus
1   1 Shihab  25  50000  HR         88                 1          8800
2   2 Kabir   30  45000  FINANCE    92                 2          8280
3   3 Mahbub  35  60000  IT         85                 3         10200
4   4 Pranto  40  45000  HR         78                 4          7020
5   5 Nusrat  28  70000  IT         90                 5         12600
6   6 Mumu    32  52000  FINANCE    94                 6          9776
7   7 Meraj   45  48000  IT         86                 7          8256
8   8 Supto   29  68000  HR         80                 8         10880
9   9 Mujahid 50  65000  FINANCE    89                 9         11570
10 10 Ashik   27  40000  IT         75                10          6000

   ID Name    Age Salary Department Performance_score Experience Bonus
1   1 Shihab  25  50000  HR         88                 1          8800
2   2 Kabir   30  45000  FINANCE    92                 2          8280
3   3 Mahbub  35  60000  IT         85                 3         10200
4   4 Pranto  40  45000  HR         78                 4          7020
5   5 Nusrat  28  70000  IT         90                 5         12600
6   6 Mumu    32  52000  FINANCE    94                 6          9776
7   7 Meraj   45  48000  IT         86                 7          8256
8   8 Supto   29  68000  HR         80                 8         10880
9   9 Mujahid 50  65000  FINANCE    89                 9         11570
10 10 Ashik   27  40000  IT         75                10          6000

   ID Name    Age Salary Department Experience Constant_value Bonus
1   1 Shihab  25  50000  HR          2         1              4400
2   2 Kabir   30  45000  FINANCE     5         1              4140
3   3 Mahbub  35  60000  IT         10         1              5100
4   4 Pranto  40  45000  HR          3         1              3510
5   5 Nusrat  28  70000  IT          8         1              6300
6   6 Mumu    32  52000  FINANCE     4         1              4888
7   7 Meraj   45  48000  IT          2         1              4128
8   8 Supto   29  68000  HR          1         1              5440
9   9 Mujahid 50  65000  FINANCE     1         1              5785
10 10 Ashik   27  40000  IT          6         1              3000
   High_performer Low_performer
1   TRUE          FALSE
2   TRUE          FALSE
3   TRUE          FALSE
4  FALSE           TRUE
5   TRUE          FALSE
6   TRUE          FALSE
7   TRUE          FALSE
8  FALSE           TRUE
9   TRUE          FALSE
10 FALSE           TRUE

   ID Name    Age Salary Department Experience Bonus
1   1 Shihab  25  50000  HR          2         4400
2   2 Kabir   30  45000  FINANCE     5         4140
3   3 Mahbub  35  60000  IT         10         5100
4   4 Pranto  40  45000  HR          3         3510
5   5 Nusrat  28  70000  IT          8         6300
6   6 Mumu    32  52000  FINANCE     4         4888
7   7 Meraj   45  48000  IT          2         4128
8   8 Supto   29  68000  HR          1         5440
9   9 Mujahid 50  65000  FINANCE     1         5785
10 10 Ashik   27  40000  IT          6         3000

   Name    Department
1  Shihab  HR
2  Kabir   FINANCE
3  Mahbub  IT
4  Pranto  HR
5  Nusrat  IT
6  Mumu    FINANCE
7  Meraj   IT
8  Supto   HR
9  Mujahid FINANCE
10 Ashik   IT

In [38]:
# Editing column

## Base R ##
# Rename a column
colnames(data)[which(colnames(data) == "Salary")] <- "Monthly_salary"
data
;
# Modify an existing column
data$Age <- data$Age * 12
data


## dplyr ##
# Rename a column
data_01 <- data_01 %>% rename(Monthly_salary = Salary)
data_01

# Modify an existing column
data_01 %>% mutate(
  Age = Age *12
)

   ID Name    Age      Mothly_salary Department Performance_score Experience
1   1 Shihab   6220800 50000         HR         88                 2
2   2 Kabir    7464960 45000         FINANCE    92                 5
3   3 Mahbub   8709120 60000         IT         85                10
4   4 Pranto   9953280 45000         HR         78                 3
5   5 Nusrat   6967296 70000         IT         90                 8
6   6 Mumu     7962624 52000         FINANCE    94                 4
7   7 Meraj   11197440 48000         IT         86                 2
8   8 Supto    7216128 68000         HR         80                 1
9   9 Mujahid 12441600 65000         FINANCE    89                 1
10 10 Ashik    6718464 40000         IT         75                 6
   Constant_value Bonus High_performer Low_performer
1  1              4400   TRUE          FALSE
2  1              4140   TRUE          FALSE
3  1              5100   TRUE          FALSE
4  1              3510  FALSE           TRUE
5  1              6300   TRUE          FALSE
6  1              4888   TRUE          FALSE
7  1              4128   TRUE          FALSE
8  1              5440  FALSE           TRUE
9  1              5785   TRUE          FALSE
10 1              3000  FALSE           TRUE

   ID Name    Age       Mothly_salary Department Performance_score Experience
1   1 Shihab   74649600 50000         HR         88                 2
2   2 Kabir    89579520 45000         FINANCE    92                 5
3   3 Mahbub  104509440 60000         IT         85                10
4   4 Pranto  119439360 45000         HR         78                 3
5   5 Nusrat   83607552 70000         IT         90                 8
6   6 Mumu     95551488 52000         FINANCE    94                 4
7   7 Meraj   134369280 48000         IT         86                 2
8   8 Supto    86593536 68000         HR         80                 1
9   9 Mujahid 149299200 65000         FINANCE    89                 1
10 10 Ashik    80621568 40000         IT         75                 6
   Constant_value Bonus High_performer Low_performer
1  1              4400   TRUE          FALSE
2  1              4140   TRUE          FALSE
3  1              5100   TRUE          FALSE
4  1              3510  FALSE           TRUE
5  1              6300   TRUE          FALSE
6  1              4888   TRUE          FALSE
7  1              4128   TRUE          FALSE
8  1              5440  FALSE           TRUE
9  1              5785   TRUE          FALSE
10 1              3000  FALSE           TRUE

   ID Name    Age Monthly_salary Department Performance_score Experience Bonus
1   1 Shihab  300 50000          HR         88                 1          8800
2   2 Kabir   360 45000          FINANCE    92                 2          8280
3   3 Mahbub  420 60000          IT         85                 3         10200
4   4 Pranto  480 45000          HR         78                 4          7020
5   5 Nusrat  336 70000          IT         90                 5         12600
6   6 Mumu    384 52000          FINANCE    94                 6          9776
7   7 Meraj   540 48000          IT         86                 7          8256
8   8 Supto   348 68000          HR         80                 8         10880
9   9 Mujahid 600 65000          FINANCE    89                 9         11570
10 10 Ashik   324 40000          IT         75                10          6000

In [65]:
# Editing rows

## Base R ##
# Update values in a specific rows
data <- data %>% select(-c(High_performer,Low_performer, Constant_value))
data[data$Name == "Shihab", "Performance_score"] <- 80
data

# Add a new row
# data <- data %>% rename(Monthly_salary = Mothly_salary)
# data
new_record <- data.frame(
  ID = 11,
  Name = "Nadia",
  Age = 26,
  Monthly_salary = 55000,
  Department = "IT",
  Performance_score = 88,
  Experience = 4,
  Bonus = 50000 * 88 * 0.02
)
data_01 <- rbind(data_01, new_record)
data_01

# Removig a row
data_01 <- data_01[data_01$Name != "Nadia",]
data_01

   ID Name    Age Monthly_salary Department Performance_score Experience Bonus
1   1 Shihab  25  50000          HR         88                 1          8800
2   2 Kabir   30  45000          FINANCE    92                 2          8280
3   3 Mahbub  35  60000          IT         85                 3         10200
4   4 Pranto  40  45000          HR         78                 4          7020
5   5 Nusrat  28  70000          IT         90                 5         12600
6   6 Mumu    32  52000          FINANCE    94                 6          9776
7   7 Meraj   45  48000          IT         86                 7          8256
8   8 Supto   29  68000          HR         80                 8         10880
9   9 Mujahid 50  65000          FINANCE    89                 9         11570
10 10 Ashik   27  40000          IT         75                10          6000
11 11 Nadia   26  55000          IT         88                 4         88000

   ID Name    Age Monthly_salary Department Performance_score Experience Bonus
1   1 Shihab  25  50000          HR         88                 1          8800
2   2 Kabir   30  45000          FINANCE    92                 2          8280
3   3 Mahbub  35  60000          IT         85                 3         10200
4   4 Pranto  40  45000          HR         78                 4          7020
5   5 Nusrat  28  70000          IT         90                 5         12600
6   6 Mumu    32  52000          FINANCE    94                 6          9776
7   7 Meraj   45  48000          IT         86                 7          8256
8   8 Supto   29  68000          HR         80                 8         10880
9   9 Mujahid 50  65000          FINANCE    89                 9         11570
10 10 Ashik   27  40000          IT         75                10          6000

In [91]:


# Editing rows

## dplyr ##
# Update values in a specific row
data <- data %>% mutate(
  Performance_score = if_else(Name == "Shihab", 80, Performance_score)
)
data


# Add a new row
new_record <- data.frame(
  ID = 11,
  Name = "Nadia",
  Age = 26,
  Salary = 55000,
  Department = "IT",
  Performance_score = 88
)

data <- bind_rows(data,new_record)
data

# Removing a row
data <- data %>% filter(Name != "Nadia")
data

# Arrange data

# data <- data %>%
#   arrange(Department, desc(Performance_score))
# data

   ID Name    Age Salary Department Performance_score
1   1 Shihab  25  50000  HR         88
2   2 Kabir   30  45000  FINANCE    92
3   3 Mahbub  35  60000  IT         85
4   4 Pranto  40  45000  HR         78
5   5 Nusrat  28  70000  IT         90
6   6 Mumu    32  52000  FINANCE    94
7   7 Meraj   45  48000  IT         86
8   8 Supto   29  68000  HR         80
9   9 Mujahid 50  65000  FINANCE    89
10 10 Ashik   27  40000  IT         75
11 11 Nadia   26  55000  IT         88

   ID Name    Age Salary Department Performance_score
1   1 Shihab  25  50000  HR         88
2   2 Kabir   30  45000  FINANCE    92
3   3 Mahbub  35  60000  IT         85
4   4 Pranto  40  45000  HR         78
5   5 Nusrat  28  70000  IT         90
6   6 Mumu    32  52000  FINANCE    94
7   7 Meraj   45  48000  IT         86
8   8 Supto   29  68000  HR         80
9   9 Mujahid 50  65000  FINANCE    89
10 10 Ashik   27  40000  IT         75

In [98]:
install.packages("tidyr")
library(tidyr)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [100]:
# Reshaping
# Reshaping needs a new package called "tidyr"
data_wide <- data.frame(
  country = c("BD","Ghana","UK","Canada"),
  continent = c("Asia","Africa","Europe","North America"),
  GDP_1960 = c(10,20,30,40),
  GDP_1970 = c(13,23,33,45),
  GDP_1980 = c(15,25,35,60)
)
data_wide



data_long <- data_wide %>%
  pivot_longer(
  cols = starts_with("GDP_"),
  names_to = "Year",
  names_prefix = "GDP_",
  values_to = "GDP"
  )

data_long

data_wide_back <- data_long %>%
  pivot_wider(
  names_from = "Year",
  values_from = "GDP",
  names_prefix = "GDP_"
  )
data_wide_back

  country continent     GDP_1960 GDP_1970 GDP_1980
1 BD      Asia          10       13       15
2 Ghana   Africa        20       23       25
3 UK      Europe        30       33       35
4 Canada  North America 40       45       60

   country continent     Year GDP
1  BD      Asia          1960 10
2  BD      Asia          1970 13
3  BD      Asia          1980 15
4  Ghana   Africa        1960 20
5  Ghana   Africa        1970 23
6  Ghana   Africa        1980 25
7  UK      Europe        1960 30
8  UK      Europe        1970 33
9  UK      Europe        1980 35
10 Canada  North America 1960 40
11 Canada  North America 1970 45
12 Canada  North America 1980 60

  country continent     GDP_1960 GDP_1970 GDP_1980
1 BD      Asia          10       13       15
2 Ghana   Africa        20       23       25
3 UK      Europe        30       33       35
4 Canada  North America 40       45       60

In [104]:
# Joinig datasets
employess <- data.frame(
  ID = c(1,2,3,4,5),
  Name = c("Shihab","Kabir","Maidul","Sanjoy","Akash"),
  Department = c("HR","IT","HR","IT","IT")
)

salaries <- data.frame(
  ID = c(1,2,3,4,6),
  Salary = c(50000,60000,70000,80000,75000)
)

left_join(employess,salaries, by = "ID")
right_join(employess,salaries, by = "ID")
inner_join(employess,salaries, by = "ID")
full_join(employess,salaries, by = "ID")

  ID Name   Department Salary
1 1  Shihab HR         50000
2 2  Kabir  IT         60000
3 3  Maidul HR         70000
4 4  Sanjoy IT         80000
5 5  Akash  IT            NA

  ID Name   Department Salary
1 1  Shihab HR         50000
2 2  Kabir  IT         60000
3 3  Maidul HR         70000
4 4  Sanjoy IT         80000
5 6  NA     NA         75000

  ID Name   Department Salary
1 1  Shihab HR         50000
2 2  Kabir  IT         60000
3 3  Maidul HR         70000
4 4  Sanjoy IT         80000

  ID Name   Department Salary
1 1  Shihab HR         50000
2 2  Kabir  IT         60000
3 3  Maidul HR         70000
4 4  Sanjoy IT         80000
5 5  Akash  IT            NA
6 6  NA     NA         75000