In [ ]:
# Remaining Matrix

mat1 <- matrix(c(1,2,3,4,5,6,7,8,9), nrow = 3, ncol = 3, byrow = TRUE)
mat2 <- matrix(c(9,8,7,6,5,4,3,2,1), nrow = 3, ncol = 3, byrow = TRUE)
print("------Summation-------")
print("------------------------")
mat1 + mat2
print("------Substraction--------")
print("------------------------")
mat2 - mat1
print("-----Multiplication-------")
print("------------------------")
mat1 * mat2
print("-----Division------")
print("------------------------")
mat1 / mat2
print("-----Matrix Multiplication-------")
print("------------------------")
mat1 %*% mat2
print("-----Summation a particular number to element---------")
print("------------------------")
mat1+10
print("-----Substraction a particular number to element---------")
print("------------------------")
mat2-3



# Diagonal of a matrix
diag(mat1)

# Inverse of a matrix

[1] "------Summation-------"
[1] "------------------------"

     [,1] [,2] [,3]
[1,] 10   10   10
[2,] 10   10   10
[3,] 10   10   10

[1] "------Substraction--------"
[1] "------------------------"

     [,1] [,2] [,3]
[1,]  8    6    4
[2,]  2    0   -2
[3,] -4   -6   -8

[1] "-----Multiplication-------"
[1] "------------------------"

     [,1] [,2] [,3]
[1,]  9   16   21
[2,] 24   25   24
[3,] 21   16    9

[1] "-----Division------"
[1] "------------------------"

     [,1]      [,2] [,3]
[1,] 0.1111111 0.25 0.4285714
[2,] 0.6666667 1.00 1.5000000
[3,] 2.3333333 4.00 9.0000000

[1] "-----Modolus-------"
[1] "------------------------"

     [,1] [,2] [,3]
[1,]  30   24  18
[2,]  84   69  54
[3,] 138  114  90

[1] "-----Summation a particular number to element---------"
[1] "------------------------"

     [,1] [,2] [,3]
[1,] 11   12   13
[2,] 14   15   16
[3,] 17   18   19

[1] "-----Substraction a particular number to element---------"
[1] "------------------------"

     [,1] [,2] [,3]
[1,] 6     5    4
[2,] 3     2    1
[3,] 0    -1   -2

[1] 1 5 9

In [9]:
# Dataframe Remaining
df1 <- data.frame(
  ID = c(1,2,3,4),
  Age = c(22,33,23,22),
  Gender = c("F","F","M","M"),
  Location = c("rural","urban","rural","sub-urban"),
  stringsAsFactors = TRUE
)

df1
is.data.frame(df1)
summary(df1)

is.character(c("F","F","M","M"))
is.factor(as.factor(c("F","F","M","M")))      # converts character to factor(assign numeric value to each data) and checks is it a factor or not
is.numeric(as.factor(c("F","F","M","M")))    # checks if originally vector is a factor or converted to factor

# Subsetting
df1$ID
df1$Age
df1$Gender
df1$Location
mean(df1$Age)

df2 <- data.frame(
  ID = c(1,2,3,4),
  Age = c(22,33,23,NA),
  Gender = c("F","F","M","M"),
  Location = c("rural","urban","rural","sub-urban"),
  stringsAsFactors = TRUE
)
df2
mean(df2$Age, na.rm = TRUE)

  ID Age Gender Location
1 1  22  F      rural
2 2  33  F      urban
3 3  23  M      rural
4 4  22  M      sub-urban

[1] TRUE

       ID            Age       Gender      Location
 Min.   :1.00   Min.   :22.0   F:2    rural    :2
 1st Qu.:1.75   1st Qu.:22.0   M:2    sub-urban:1
 Median :2.50   Median :22.5          urban    :1
 Mean   :2.50   Mean   :25.0
 3rd Qu.:3.25   3rd Qu.:25.5
 Max.   :4.00   Max.   :33.0

[1] TRUE

[1] TRUE

[1] FALSE

[1] 1 2 3 4

[1] 22 33 23 22

[1] F F M M
Levels: F M

[1] rural     urban     rural     sub-urban
Levels: rural sub-urban urban

[1] 25

  ID Age Gender Location
1 1  22  F      rural
2 2  33  F      urban
3 3  23  M      rural
4 4  NA  M      sub-urban

[1] 26

In [18]:
# Row and Column Names
colnames(df1) <- c("Id","Age","Gender","Location")
colnames(df1)
colnames(df1) == "Age"
colnames(df1)[colnames(df1) == "Age"] <- "Age_Of_Respondant"
colnames(df1)

rownames(df1)
rownames(df1) <- c("Person1","Person2","Person3","Person4")
df1

[1] "Id"       "Age"      "Gender"   "Location"

[1] FALSE  TRUE FALSE FALSE

[1] "Id"                "Age_Of_Respondant" "Gender"
[4] "Location"

[1] "Person1" "Person2" "Person3" "Person4"

        Id Age_Of_Respondant Gender Location
Person1 1  22                F      rural
Person2 2  33                F      urban
Person3 3  23                M      rural
Person4 4  22                M      sub-urban

In [25]:
# Filtering
df1[2,]
df1[c(1,4),]
df1$Age_Of_Respondant < 23
!is.na(df1$Age_Of_Respondant)
df1[df1$Age_Of_Respondant < 23 & !is.na(df1$Age_Of_Respondant),]



# Add column
df1$Height <- c(5.2,5.7,5.9,6.0)
df1
df1$Age_In_Month <- df1$Age_Of_Respondant*12
df1

        Id Age_Of_Respondant Gender Location Height
Person2 2  33                F      urban    5.7

        Id Age_Of_Respondant Gender Location  Height
Person1 1  22                F      rural     5.2
Person4 4  22                M      sub-urban 6.0

[1]  TRUE FALSE FALSE  TRUE

[1] TRUE TRUE TRUE TRUE

        Id Age_Of_Respondant Gender Location  Height
Person1 1  22                F      rural     5.2
Person4 4  22                M      sub-urban 6.0

        Id Age_Of_Respondant Gender Location  Height
Person1 1  22                F      rural     5.2
Person2 2  33                F      urban     5.7
Person3 3  23                M      rural     5.9
Person4 4  22                M      sub-urban 6.0

        Id Age_Of_Respondant Gender Location  Height Age_In_Month
Person1 1  22                F      rural     5.2    264
Person2 2  33                F      urban     5.7    396
Person3 3  23                M      rural     5.9    276
Person4 4  22                M      sub-urban 6.0    264

In [44]:
# List
ls1 <- list(c(1,2,3,4),c(24,25,26),c("F","M","F","M","M"))
ls1
ls1[[1]]
ls1[[3]][5]
ls1[[2]][4]

ls2 <-list(id = c(1,2,3,4), age = c(22,28,32), df = df1)
ls2
ls2$df
is.data.frame(ls2)
is.data.frame(ls2$df)
str(ls2)

arr1 <- array(c(1:15),c(3,3,2))
print(arr1)

ls3 <- list(id =c(1,2,3,4), Age = c(22,21,25,24,26), df=df1, array1 = arr1)
print(ls3)

[[1]]
[1] 1 2 3 4

[[2]]
[1] 24 25 26

[[3]]
[1] "F" "M" "F" "M" "M"

[1] 1 2 3 4

[1] "M"

[1] NA

$id
[1] 1 2 3 4

$age
[1] 22 28 32

$df
        Id Age_Of_Respondant Gender  Location Height Age_In_Month
Person1  1                22      F     rural    5.2          264
Person2  2                33      F     urban    5.7          396
Person3  3                23      M     rural    5.9          276
Person4  4                22      M sub-urban    6.0          264

        Id Age_Of_Respondant Gender Location  Height Age_In_Month
Person1 1  22                F      rural     5.2    264
Person2 2  33                F      urban     5.7    396
Person3 3  23                M      rural     5.9    276
Person4 4  22                M      sub-urban 6.0    264

[1] FALSE

[1] TRUE

List of 3
 $ id : num [1:4] 1 2 3 4
 $ age: num [1:3] 22 28 32
 $ df :'data.frame':	4 obs. of  6 variables:
  ..$ Id               : num [1:4] 1 2 3 4
  ..$ Age_Of_Respondant: num [1:4] 22 33 23 22
  ..$ Gender           : Factor w/ 2 levels "F","M": 1 1 2 2
  ..$ Location         : Factor w/ 3 levels "rural","sub-urban",..: 1 3 1 2
  ..$ Height           : num [1:4] 5.2 5.7 5.9 6
  ..$ Age_In_Month     : num [1:4] 264 396 276 264
, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13    1
[2,]   11   14    2
[3,]   12   15    3

$id
[1] 1 2 3 4

$Age
[1] 22 21 25 24 26

$df
        Id Age_Of_Respondant Gender  Location Height Age_In_Month
Person1  1                22      F     rural    5.2          264
Person2  2                33      F     urban    5.7          396
Person3  3                23      M     rural    5.9          276
Person4  4                22      M sub-urban    6.0          264

$array1
, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13    1
[2,]   11   14    2
[3,]   12   15    3

In [58]:
# Conditional Statements, Loops, Functions

# Compound Expression
  # - Simple one line expressions
  # - Multiple line expressions within curly brackets or separated by semi-colon
print("Hello world")
1+6

{
  print("Hello world")
  1+6
}

print("Hello world");1+6

# Conditionals
  x <- 2
  if(x>0){
    print("X is positive")
  }else if(x<0){
    print("X is negative")
  }else{
    print("X is zero")
  }


  x <- 7
  if(x>0){
    if(x %% 2 == 0){
      print("X is positive and even")
    }else{
      print("X is positive and odd")
    }
  }else{
    print("X is not positive")
  }

  # Vectorize version of If-else(returns a vector)
  x <- c(1,2,3,5,0,99,95)
  ifelse(x>90,"Yes","No")
  ifelse(x>90,"Yes",ifelse(x == 0, "Zero","No"))

  # Switch
  operation <- "root"
  val <- 25

  switch(
    operation,
    "square" = val*2,
    "root" = sqrt(val),
    "Invalid Operation"
  )


  # Loops

    # For loops
    numbers <- c(2,4,6,8)
    for(num in numbers){
      print(paste("Square of",num, "is: ", num^2))
    }

    # While loops
    count <- 5
    while(count>0){
      print(count)
      count <- count-1
    }

    # Repeat (will continue untill 'break' occurs)
    # repeat{
    #   print("This is an infinite loop. Press Esc to stop")
    #   Sys.sleep(1)
    # }


    counter <- 1
    repeat{
      print(counter)
      counter <- counter +1
      if(counter>5){
        break
      }
    }

[1] "Hello world"

[1] 7

[1] "Hello world"

[1] 7

[1] "Hello world"

[1] 7

[1] "X is positive"
[1] "X is positive and odd"

[1] "No"  "No"  "No"  "No"  "No"  "Yes" "Yes"

[1] "No"   "No"   "No"   "No"   "Zero" "Yes"  "Yes"

[1] 5

[1] "Square of 2 is:  4"
[1] "Square of 4 is:  16"
[1] "Square of 6 is:  36"
[1] "Square of 8 is:  64"
[1] 5
[1] 4
[1] 3
[1] 2
[1] 1
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

In [62]:
# User input(use readline() function)

x <- as.integer(readline("Enter your number:"))
x

repeat{
  input <- as.integer(readline("Enter your nubmer: "))
  if(!is.na(input) & input>1 & input<=10){
    print(paste("Your number: ", input))
    break
  }else{
    print("Invalid input!Try again.")
  }
}

Enter your number:23

[1] 23

Enter your nubmer: 22
Enter your nubmer: 11
Enter your nubmer: 10
[1] "Invalid input!Try again."
[1] "Invalid input!Try again."
[1] "Your number:  10"

In [71]:
# Apply function

mat <- matrix(1:9, nrow = 3, byrow = TRUE)
apply(mat, 1, sum)  #Sum of each row
apply(mat, 2, sum)  #Sum of each column

rowSums(mat)
colSums(mat)
rowMeans(mat)
colMeans(mat)

# Tapply function

print(tapply(X = df1$Age_Of_Respondant, INDEX = df1$Gender, FUN = mean, is.na = TRUE))
print(tapply(X = df1$Age_Of_Respondant, INDEX = list(df1$Gender, df1$Location), FUN = mean, is.na = TRUE))

# Lapply and Sapply
lapply(ls3, is.data.frame)

print(sapply(ls3, is.data.frame))

[1]  6 15 24

[1] 12 15 18

[1]  6 15 24

[1] 12 15 18

[1] 2 5 8

[1] 4 5 6

   F    M
27.5 22.5
  rural sub-urban urban
F    22        NA    33
M    23        22    NA

$id
[1] FALSE

$Age
[1] FALSE

$df
[1] TRUE

$array1
[1] FALSE

    id    Age     df array1
 FALSE  FALSE   TRUE  FALSE